# Generated by Django 3.0.2 on 2023-01-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newskg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newskg',
            options={'ordering': ['created_at'], 'verbose_name': 'IT Language', 'verbose_name_plural': 'IT Languages'},
        ),
        migrations.AlterField(
            model_name='newskg',
            name='content',
            field=models.TextField(blank=True, verbose_name='Framework'),
        ),
        migrations.AlterField(
            model_name='newskg',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='newskg',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Language'),
        ),
    ]
