# Generated by Django 3.0.2 on 2023-01-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newskg', '0003_auto_20230115_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purpose',
            options={'ordering': ['id'], 'verbose_name': 'Purpose', 'verbose_name_plural': 'Purposes'},
        ),
        migrations.AddField(
            model_name='newskg',
            name='info',
            field=models.TextField(blank=True, verbose_name='Information'),
        ),
    ]
